require("dotenv").config();
const express=require("express"),path=require("path"),fs=require("fs"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),crypto=require("crypto");
const app=express();
app.use(express.json({limit:"2mb"}));
const PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||"change-me",ADMIN_EMAIL=(process.env.ADMIN_EMAIL||"admin@goodnewsshopping.com").toLowerCase(),ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"ChangeMe123!",DB=process.env.DB_FILE||path.join(__dirname,"data.json");
let db={users:[],products:[],orders:[],categories:[]};
if(fs.existsSync(DB))try{db=JSON.parse(fs.readFileSync(DB))}catch{}
function save(){fs.writeFileSync(DB,JSON.stringify(db,null,2))}
const pics={phone:"https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",laptop:"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",audio:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",tv:"https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=900&q=80",fashion:"https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80",shoes:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",home:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",watch:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80"};
if(!db.products.length){
 db.categories=[["Phones & Tablets","📱"],["Computing","💻"],["Electronics","🎧"],["TV & Audio","📺"],["Fashion","👕"],["Shoes","👟"],["Beauty","✨"],["Home","🏠"],["Appliances","🧺"],["Groceries","🛒"],["Gaming","🎮"],["Accessories","⌚"],["Baby","🍼"],["Sports","⚽"],["Books","📚"],["Office","🖨️"]].map(x=>({name:x[0],icon:x[1]}));
 const seed=[["Nova X Pro 5G","Phones & Tablets",365000,410000,pics.phone],["GoodPhone Max 256GB","Phones & Tablets",289000,330000,pics.phone],["AirBook 15 Laptop","Computing",650000,720000,pics.laptop],["Pro Wireless Headphones","Electronics",85000,105000,pics.audio],["55-inch Smart TV 4K","TV & Audio",520000,600000,pics.tv],["Classic Fashion Set","Fashion",45000,60000,pics.fashion],["Urban Runner Sneakers","Shoes",68000,80000,pics.shoes],["Modern Sofa","Home",380000,420000,pics.home],["Smart Watch Series","Accessories",95000,120000,pics.watch]];
 db.products=seed.map((x,i)=>({id:"P"+(i+1),name:x[0],category:x[1],price:x[2],oldPrice:x[3],image:x[4],rating:4.7,stock:20,deal:i<4,description:"Quality product from Good News Shopping."}));save()
}
if(!db.categories?.length){db.categories=[];save()}
function uid(p){return p+"-"+crypto.randomBytes(5).toString("hex").toUpperCase()}
function safe(u){return {id:u.id,name:u.name,email:u.email,role:u.role,createdAt:u.createdAt}}
function tok(u){return jwt.sign({id:u.id,email:u.email,role:u.role},SECRET,{expiresIn:"7d"})}
function auth(req,res,next){let h=req.headers.authorization||"";try{req.user=jwt.verify(h.replace("Bearer ",""),SECRET);next()}catch{res.status(401).json({message:"Please sign in."})}}
function admin(req,res,next){if(req.user.role!=="admin")return res.status(403).json({message:"Admin only."});next()}
function cleanProduct(body,existing={}){return {name:String(body.name??existing.name??"").trim(),category:String(body.category??existing.category??"").trim(),price:Number(body.price??existing.price??0),oldPrice:Number(body.oldPrice??existing.oldPrice??0),image:String(body.image??existing.image??"").trim(),stock:Math.max(0,Math.floor(Number(body.stock??existing.stock??0))),rating:Number(body.rating??existing.rating??4.5)||4.5,deal:Boolean(body.deal??existing.deal??false),description:String(body.description??existing.description??"").trim()}}

app.use(express.static(path.join(__dirname,"public")));
app.get("/api/products",(q,r)=>r.json({products:db.products,categories:db.categories}));
app.post("/api/auth/register",async(q,r)=>{let{name,email,password}=q.body||{},e=String(email||"").trim().toLowerCase();if(!name||!e||!password)return r.status(400).json({message:"All fields are required."});if(password.length<6)return r.status(400).json({message:"Password must be at least 6 characters."});if(db.users.some(u=>u.email===e))return r.status(409).json({message:"Email already registered."});let u={id:uid("USR"),name:String(name).trim(),email:e,passwordHash:await bcrypt.hash(password,12),role:"customer",createdAt:new Date().toISOString()};db.users.push(u);save();r.json({user:safe(u),token:tok(u)})});
app.post("/api/auth/login",async(q,r)=>{let{email,password}=q.body||{},e=String(email||"").trim().toLowerCase(),u=db.users.find(x=>x.email===e);if(!u&&e===ADMIN_EMAIL&&password===ADMIN_PASSWORD)u={id:"ADMIN",name:"Good News Admin",email:ADMIN_EMAIL,role:"admin",createdAt:new Date().toISOString()};if(!u)return r.status(401).json({message:"Invalid email or password."});if(u.role!=="admin"&&!await bcrypt.compare(password,u.passwordHash))return r.status(401).json({message:"Invalid email or password."});r.json({user:safe(u),token:tok(u)})});
app.get("/api/orders/my",auth,(q,r)=>r.json({orders:db.orders.filter(o=>o.userId===q.user.id).reverse()}));

async function notify(o){let token=process.env.WHATSAPP_ACCESS_TOKEN,id=process.env.WHATSAPP_PHONE_NUMBER_ID,to=process.env.ADMIN_WHATSAPP;if(!token||!id||!to){console.log("WhatsApp Cloud API not configured for",o.orderNumber);return}let body=`New order ${o.orderNumber}\nCustomer: ${o.customer.name}\nPhone: ${o.customer.phone}\nTotal: ₦${o.total.toLocaleString()}`;try{let x=await fetch(`https://graph.facebook.com/v23.0/${id}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to,type:"text",text:{body}})});console.log(await x.json())}catch(e){console.error(e.message)}}
app.post("/api/orders",auth,async(q,r)=>{let{name,phone,state,city,address,paymentMethod,items}=q.body||{};if(!name||!phone||!state||!city||!address||!items?.length)return r.status(400).json({message:"Complete checkout first."});let total=0,out=[];for(let i of items){let p=db.products.find(x=>x.id===i.productId),qty=Math.max(1,Number(i.qty));if(!p||p.stock<qty)return r.status(400).json({message:"Product unavailable or out of stock."});p.stock-=qty;total+=p.price*qty;out.push({productId:p.id,name:p.name,price:p.price,qty,image:p.image})}let delivery=total>500000?0:2500,o={id:uid("ORD"),orderNumber:"GN-"+Math.floor(10000000+Math.random()*89999999),userId:q.user.id,customer:{name,phone,state,city,address},paymentMethod,items:out,subtotal:total,delivery,total:total+delivery,status:"placed",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.orders.push(o);save();notify(o);r.status(201).json({order:o})});

// Admin: products
app.get("/api/admin/products",auth,admin,(q,r)=>r.json({products:db.products,categories:db.categories}));
app.post("/api/admin/products",auth,admin,(q,r)=>{let p=cleanProduct(q.body||{});if(!p.name||!p.category||!p.price||!p.image)return r.status(400).json({message:"Name, category, price and image are required."});if(!db.categories.some(c=>c.name===p.category)){db.categories.push({name:p.category,icon:"🛍️"})}let product={id:uid("P"),...p};db.products.unshift(product);save();r.status(201).json({product})});
app.patch("/api/admin/products/:id",auth,admin,(q,r)=>{let i=db.products.findIndex(x=>x.id===q.params.id);if(i<0)return r.status(404).json({message:"Product not found."});let p=cleanProduct(q.body||{},db.products[i]);if(!p.name||!p.category||!p.price||!p.image)return r.status(400).json({message:"Name, category, price and image are required."});if(!db.categories.some(c=>c.name===p.category))db.categories.push({name:p.category,icon:"🛍️"});db.products[i]={...db.products[i],...p};save();r.json({product:db.products[i]})});
app.delete("/api/admin/products/:id",auth,admin,(q,r)=>{let i=db.products.findIndex(x=>x.id===q.params.id);if(i<0)return r.status(404).json({message:"Product not found."});let [removed]=db.products.splice(i,1);save();r.json({product:removed})});

app.get("/api/admin/orders",auth,admin,(q,r)=>r.json({orders:[...db.orders].reverse()}));
app.patch("/api/admin/orders/:id",auth,admin,(q,r)=>{let o=db.orders.find(x=>x.id===q.params.id);if(!o)return r.status(404).json({message:"Order not found."});o.status=q.body.status;o.updatedAt=new Date().toISOString();save();r.json({order:o})});
app.get("/api/health",(q,r)=>r.json({ok:true}));
app.get("/admin",(q,r)=>r.sendFile(path.join(__dirname,"public/admin/index.html")));
app.get("*",(q,r)=>r.sendFile(path.join(__dirname,"public/index.html")));
app.listen(PORT,()=>console.log(`Good News Shopping: http://localhost:${PORT}`));
